stages:
   - build

build:
   stage: build
   image: node:16.13.0-stretch
   only:
      - tags
   script: 
      - echo 'install dependencies'
      - npm install
      - echo 'build project'
      - npm run build
   artifacts:
      paths:
         - build/