stages:
   - build
   - deploy

build:
   stage: build
   image: node:14.15.0-stretch
   script: 
      - echo 'install dependencies'
      - npm install
      - echo 'build project'
      - npm run build
   artifacts:
      paths:
         - build/
   
deploy:
   stage: deploy
   image: python:latest
   script:
      - echo 'install awscli with pip python'
      - pip install awscli
      - aws s3 sync ./build s3://staging-cicd-ecocrew